failure:
  # (string or pattern to check): (failure comments to be posted by Danger if key string exists)
  'SomeDeprecatedFunc': 'You should use XXX'
warning:
  # (string to check): (warning comment to be posted by Danger if key string exists)
  'TODO': 'You should check!'
